### ISSUE TITLE
Create BaseFolder under assets when subsite is created?

### ISSUE THREAD

**Issue by michalkleiner** [lekoala/silverstripe-subsites-extras#8]
Hi Thomas,

I see there's a BaseFolder field, which gets auto-populated from the subsite title if it's left blank.

It doesn't seem to have any impact anywhere else in the code. Was the original intention to maybe automatically create the folder under site assets and perhaps provide an extension to UploadField prefixing its path with this folder?

Cheers
Michal

**Comment by lekoala** [comment]
indeed! if you have a look at my form-extras module, you will see it's being used.

but you can also simply use it manually. the idea being that each subsite store it's assets into one folder, except for shared assets.

but really, after trying that, i'm not convinced it's much better to just share all assets across websites (it's just really confusing to have some files belonging to a specific subsite)

**Comment by michalkleiner** [comment]
We have a use-case where it's desired to keep subsite assets as separated as possible. Basically, the main site doesn't have any function in the project, everything is a subsite.
I've created a tiny subsite extension that we're using which creates the folder onAfterWrite when subsite is created, adding its ID to the folder so it directly gets the limited visibility.

After a second thought, I don't think it's necessary for this module to create the folders as they get created when they are used by a file upload field, so this can be closed. Cheers.

**Comment by lekoala** [comment]
Ok, i'll close it. Folders will be created anyway upon upload. It's quite easy to override the default UploadField with a class of your own that will properly set the basefolder according to the current subsite.
